# Add to your existing pubspec.yaml file
# This is only the dependencies section - you'll need to add this to your existing file

dependencies:
  flutter:
    sdk: flutter
  # Existing dependencies...

  # Add these new dependencies for messaging functionality
  uuid: ^3.0.7        # For generating unique IDs
  image_picker: ^0.8.7  # For selecting images
  timeago: ^3.4.0     # For formatting timestamps
